//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroepswerkTaak1.DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroepswerkTaak1.DAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Image.
        /// </summary>
        internal static string D_Image {
            get {
                return ResourceManager.GetString("D_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Knop.
        /// </summary>
        internal static string D_Knop {
            get {
                return ResourceManager.GetString("D_Knop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Rol.
        /// </summary>
        internal static string D_Rol {
            get {
                return ResourceManager.GetString("D_Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_User.
        /// </summary>
        internal static string D_User {
            get {
                return ResourceManager.GetString("D_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Image.
        /// </summary>
        internal static string I_Image {
            get {
                return ResourceManager.GetString("I_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Knop.
        /// </summary>
        internal static string I_Knop {
            get {
                return ResourceManager.GetString("I_Knop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Logging.
        /// </summary>
        internal static string I_Logging {
            get {
                return ResourceManager.GetString("I_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Rol.
        /// </summary>
        internal static string I_Rol {
            get {
                return ResourceManager.GetString("I_Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_User.
        /// </summary>
        internal static string I_User {
            get {
                return ResourceManager.GetString("I_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ImageFull.
        /// </summary>
        internal static string S_ImageFull {
            get {
                return ResourceManager.GetString("S_ImageFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Images.
        /// </summary>
        internal static string S_Images {
            get {
                return ResourceManager.GetString("S_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Knop.
        /// </summary>
        internal static string S_Knop {
            get {
                return ResourceManager.GetString("S_Knop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Logging.
        /// </summary>
        internal static string S_Logging {
            get {
                return ResourceManager.GetString("S_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Rol.
        /// </summary>
        internal static string S_Rol {
            get {
                return ResourceManager.GetString("S_Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_User.
        /// </summary>
        internal static string S_User {
            get {
                return ResourceManager.GetString("S_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SV_Login.
        /// </summary>
        internal static string SV_Login {
            get {
                return ResourceManager.GetString("SV_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Image.
        /// </summary>
        internal static string U_Image {
            get {
                return ResourceManager.GetString("U_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Knop.
        /// </summary>
        internal static string U_Knop {
            get {
                return ResourceManager.GetString("U_Knop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Rol.
        /// </summary>
        internal static string U_Rol {
            get {
                return ResourceManager.GetString("U_Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_User.
        /// </summary>
        internal static string U_User {
            get {
                return ResourceManager.GetString("U_User", resourceCulture);
            }
        }
    }
}
